const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';
const REGISTER_CLEAR_PROPS = 'REGISTER_CLEAR_PROPS';

const EDITPROFILE_REQUEST = 'EDITPROFILE_REQUEST';
const EDITPROFILE_SUCCESS = 'EDITPROFILE_SUCCESS';
const EDITPROFILE_FAILURE = 'EDITPROFILE_FAILURE';
const EDITPROFILE_CLEAR_PROPS = 'EDITPROFILE_CLEAR_PROPS';

const VIEWPROFILE_REQUEST = 'VIEWPROFILE_REQUEST';
const VIEWPROFILE_SUCCESS = 'VIEWPROFILE_SUCCESS';
const VIEWPROFILE_FAILURE = 'VIEWPROFILE_FAILURE';
const VIEWPROFILE_CLEAR_PROPS = 'VIEWPROFILE_CLEAR_PROPS';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const CLEAR_PROPS = 'CLEAR_PROPS';

const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
const CHANGEPASSWORD_FAILURE = 'CHANGEPASSWORD_FAILURE';

const FORGETPASSWORD_REQUEST = 'FORGETPASSWORD_REQUEST';
const FORGETPASSWORD_SUCCESS = 'FORGETPASSWORD_SUCCESS';
const FORGETPASSWORD_FAILURE = 'FORGETPASSWORD_FAILURE';

const ROLESELECT_REQUEST = 'ROLESELECT_REQUEST';
const ROLESELECT_SUCCESS = 'ROLESELECT_SUCCESS';
const ROLESELECT_FAILURE = 'ROLESELECT_FAILURE';
const ROLESELECT_CLEAR_PROPS = 'ROLESELECT_CLEAR_PROPS';

const ADDSERVICERATE_REQUEST = 'ADDSERVICERATE_REQUEST';
const ADDSERVICERATE_SUCCESS = 'ADDSERVICERATE_SUCCESS';
const ADDSERVICERATE_FAILURE = 'ADDSERVICERATE_FAILURE';



const STRIPEACCOUNT_REQUEST = 'STRIPEACCOUNT_REQUEST';
const STRIPEACCOUNT_SUCCESS = 'STRIPEACCOUNT_SUCCESS';
const STRIPEACCOUNT_FAILURE = 'STRIPEACCOUNT_FAILURE';
const STRIPEACCOUNT_CLEAR_PROPS = 'STRIPEACCOUNT_CLEAR_PROPS';


const VIEWREQUEST_REQUEST = 'VIEWREQUEST_REQUEST';
const VIEWREQUEST_SUCCESS = 'VIEWREQUEST_SUCCESS';
const VIEWREQUEST_FAILURE = 'VIEWREQUEST_FAILURE';
const VIEWREQUEST_CLEAR_PROPS = 'VIEWREQUEST_CLEAR_PROPS';

const CREATEFEEDBACK_REQUEST = 'CREATEFEEDBACK_REQUEST';
const CREATEFEEDBACK_SUCCESS = 'CREATEFEEDBACK_SUCCESS';
const CREATEFEEDBACK_FAILURE = 'CREATEFEEDBACK_FAILURE';
const CREATEFEEDBACK_CLEAR_PROPS = 'CREATEFEEDBACK_CLEAR_PROPS';


const GETREVIEW_REQUEST = 'GETREVIEW_REQUEST';
const GETREVIEW_SUCCESS = 'GETREVIEW_SUCCESS';
const GETREVIEW_FAILURE = 'GETREVIEW_FAILURE';
const GETREVIEW_CLEAR_PROPS = 'GETREVIEW_CLEAR_PROPS';

const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
const NOTIFICATION_CLEAR_PROPS = 'NOTIFICATION_CLEAR_PROPS';

const TESTJOB_REQUEST = 'TESTJOB_REQUEST';
const TESTJOB_SUCCESS = 'TESTJOB_SUCCESS';
const TESTJOB_FAILURE = 'TESTJOB_FAILURE';
const TESTJOB_CLEAR_PROPS = 'TESTJOB_CLEAR_PROPS';

const GETWAITER_REQUEST = 'GETWAITER_REQUEST';
const GETWAITER_SUCCESS = 'GETWAITER_SUCCESS';
const GETWAITER_FAILURE = 'GETWAITER_FAILURE';

const SENDREQUESTPROFILE_REQUEST = 'SENDREQUESTPROFILE_REQUEST';
const SENDREQUESTPROFILE_SUCCESS = 'SENDREQUESTPROFILE_SUCCESS';
const SENDREQUESTPROFILE_FAILURE = 'SENDREQUESTPROFILE_FAILURE';

const SENDREQUEST_REQUEST = 'SENDREQUEST_REQUEST';
const SENDREQUEST_SUCCESS = 'SENDREQUEST_SUCCESS';
const SENDREQUEST_FAILURE = 'SENDREQUEST_FAILURE';

const CHOOSETASK_REQUEST = 'CHOOSETASK_REQUEST';
const CHOOSETASK_SUCCESS = 'CHOOSETASK_SUCCESS';
const CHOOSETASK_FAILURE = 'CHOOSETASK_FAILURE';

const VIEWSERVICEREQUEST_REQUEST = 'VIEWSERVICEREQUEST_REQUEST';
const VIEWSERVICEREQUEST_SUCCESS = 'VIEWSERVICEREQUEST_SUCCESS';
const VIEWSERVICEREQUEST_FAILURE = 'VIEWSERVICEREQUEST_FAILURE';
